# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


puts ""
puts "#####  88_tariff.rb  #####"


puts "88_tariff.rb load ... start..."

tariffs = Tariff.create([
    { #id: 1,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 0 - 4',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 4,
      condition_str: nil,
      tariff_percent: 0.00, 
      tariff_value: nil },
    { #id: 2,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 5 - 10',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 10,
      condition_str: nil,
      tariff_percent: -45.00, 
      tariff_value: nil },
    { #id: 3,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 11 - 30',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 30,
      condition_str: nil,
      tariff_percent: -50.00, 
      tariff_value: nil },
    { #id: 4,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 31 - 50',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 50,
      condition_str: nil,
      tariff_percent: -55.00, 
      tariff_value: nil },
    { #id: 5,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 51 - 100',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 100,
      condition_str: nil,
      tariff_percent: -60.00, 
      tariff_value: nil },
    { #id: 6,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 101 - 250',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 250,
      condition_str: nil,
      tariff_percent: -65.00, 
      tariff_value: nil },
    { #id: 7,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: powyżej 250',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: true,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 100000,
      condition_str: nil,
      tariff_percent: -70.00, 
      tariff_value: nil },

    { #id: 8,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 0 - 4',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 4,
      condition_str: nil,
      tariff_percent: 0.00, 
      tariff_value: nil },
    { #id: 9,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 5 - 10',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 10,
      condition_str: nil,
      tariff_percent: -55.00, 
      tariff_value: nil },
    { #id: 10,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 11 - 30',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 30,
      condition_str: nil,
      tariff_percent: -60.00, 
      tariff_value: nil },
    { #id: 11,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 31 - 50',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 50,
      condition_str: nil,
      tariff_percent: -65.00, 
      tariff_value: nil },
    { #id: 12,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 51 - 100',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 100,
      condition_str: nil,
      tariff_percent: -70.00, 
      tariff_value: nil },
    { #id: 13,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 101 - 250',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 250,
      condition_str: nil,
      tariff_percent: -75.00, 
      tariff_value: nil },
    { #id: 14,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: powyżej 250',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: false,
      risk_group: nil,
      pay: nil,
      informal_group: false,
      condition_int: 100000,
      condition_str: nil,
      tariff_percent: -80.00, 
      tariff_value: nil },

    { #id: 15,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 0 - 4',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: true,
      condition_int: 4,
      condition_str: nil,
      tariff_percent: 0.00, 
      tariff_value: nil },
    { #id: 16,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 5 - 20',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: true,
      condition_int: 20,
      condition_str: nil,
      tariff_percent: -20.00, 
      tariff_value: nil },
    { #id: 17,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 21 - 50',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: true,
      condition_int: 50,
      condition_str: nil,
      tariff_percent: -25.00, 
      tariff_value: nil },
    { #id: 18,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: 51 - 100',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: true,
      condition_int: 100,
      condition_str: nil,
      tariff_percent: -30.00, 
      tariff_value: nil },
    { #id: 19,
      category: 'IL',
      description: 'liczba osób ubezpieczonych: powyżej 100',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: true,
      condition_int: 100000,
      condition_str: nil,
      tariff_percent: -35.00, 
      tariff_value: nil },


    { #id: 25,
      category: 'SU',
      description: 'Składka SU, GR "A/D", dla kazdych 500 zł SU - ŚW. PROPORCJONALNE',
      quotation: 'AC',
      tariff_fixed: false,
      full_range: nil,
      risk_group: 'AD',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 5.80 },
    { #id: 26,
      category: 'SU',
      description: 'Składka SU, GR "B", dla kazdych 500 zł SU - ŚW. PROPORCJONALNE',
      quotation: 'AC',
      tariff_fixed: false,
      full_range: nil,
      risk_group: 'B',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 9.20 },
    { #id: 27,
      category: 'SU',
      description: 'Składka SU, GR "A/D", dla kazdych 500 zł SU - ŚW. STAŁE',
      quotation: 'AC',
      tariff_fixed: true,
      full_range: nil,
      risk_group: 'AD',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 4.10 },
    { #id: 28,
      category: 'SU',
      description: 'Składka SU, GR "B", dla kazdych 500 zł SU - ŚW. STAŁE',
      quotation: 'AC',
      tariff_fixed: true,
      full_range: nil,
      risk_group: 'B',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 6.50 },
    { #id: 100,
      category: 'SU',
      description: 'Składka SU, Kwotacja SPECJALNA, dla kazdych 500 zł SU',
      quotation: 'B',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 3.12 },


    { #id: 115,
      category: 'LE',
      description: 'Skladka Leczenie, Kwotacja SPECJALNA, dla każdych 500 zł LE',
      quotation: 'B',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 9.60 },
    { #id: 121,
      category: 'LE',
      description: 'Skladka Leczenie, GR "A/D", dla każdych 500 zł LE',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: 'AD',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 19.50 },
    { #id: 122,
      category: 'LE',
      description: 'Skladka Leczenie, GR "B", dla każdych 500 zł LE',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: 'B',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 25.50 },


    { #id: 118,
      category: 'SZ',
      description: 'Skladka Szpital, Kwotacja SPECJALNA, dla każdych 5 zł SZ',
      quotation: 'B',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 3.00 },
    { #id: 66,
      category: 'SZ',
      description: 'Skladka Szpital, GR "A/D", dla każdych 5 zł SZ',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: 'AD',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 5.00 },
    { #id: 67,
      category: 'SZ',
      description: 'Skladka Szpital, GR "B", dla każdych 5 zł SZ',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: 'B',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 10.00 },


    { #id: 112,
      category: 'ZU',
      description: 'Skladka Zawal, Kwotacja SPECJALNA, dla każdych 500 zł ZU',
      quotation: 'B',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 2.40 },
    { #id: 42, 126
      category: 'ZU',
      description: 'Skladka Zawał, GR "A/B/D", dla każdych 500 zł ZU',
      quotation: 'AC',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: nil,
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 5.00 },


    { #id: 131,
      category: 'TN',
      description: 'Skladka Niezdolność, Kwotacja SPECJALNA, dla każdych 500 zł TN',
      quotation: 'C',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: 'AB',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 6.60 },
    { #id: 34
      category: 'TN',
      description: 'Skladka Niezdolność, GR "A/B", dla każdych 500 zł ZU',
      quotation: 'A',
      tariff_fixed: nil,
      full_range: nil,
      risk_group: 'AB',
      pay: nil,
      informal_group: nil,
      condition_int: nil,
      condition_str: nil,
      tariff_percent: nil, 
      tariff_value: 3.30 }



])

puts "Tariff all: #{Tariff.all.size}"


puts "#####  END OF 88_tariff.rb  #####"
puts ""
